apps/skyscraper_web/lib/skyscraper_web/router.ex
defmodule SkyscraperWeb.Router do
  use SkyscraperWeb, :router

  use Pow.Phoenix.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SkyscraperWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :set_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :protected do
    plug(Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
    )
  end

  scope "/" do
    pipe_through :browser

    pow_routes()
  end

  scope "/", SkyscraperWeb do
    pipe_through :browser

    live "/", PageLive, :index
    live "/construct/:id", ConstructLive
  end

  scope "/", SkyscraperWeb do
    pipe_through([:browser, :protected])

    get("/building", BuildingController, :edit)
    post("/building", BuildingController, :create)
    put("/building", BuildingController, :update)

    post("/construct", ConstructController, :create)
    delete("/construct", ConstructController, :destroy)
  end

  # Other scopes may use custom stacks.
  # scope "/api", SkyscraperWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: SkyscraperWeb.Telemetry
    end
  end

  def set_current_user(conn, _params) do
    case Pow.Plug.current_user(conn) do
      nil -> conn
      user -> conn |> assign(:current_user, user |> Skyscraper.Repo.preload(:building))
    end
  end
end

apps/skyscraper_web/lib/skyscraper_web/views/layout_view.ex
defmodule SkyscraperWeb.LayoutView do
  use SkyscraperWeb, :view

  def skyscraper_active?(building), do: SkyscraperOtp.active?(building.name)
end

apps/skyscraper_web/lib/skyscraper_web/templates/layout/app.html.eex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

apps/skyscraper_web/lib/skyscraper_web/templates/layout/live.html.leex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

apps/skyscraper_web/lib/skyscraper_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Skyscraper" %>
        <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;1,100;1,300&display=swap" rel="stylesheet">
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
       <header class="header">
        <div class="header__container container">
          <%= link "Skyscraper", to: Routes.page_path(@conn, :index), class: "header__logo logo" %>
            <nav class="header__navigation navigation">
                <ul class="navigation__list">
                  <%= if @current_user do %>
                    <li class="navigation__item"><%= link "Sign out", to: Routes.pow_session_path(@conn, :delete), method: :delete, class: "navigation__link" %></li>
                    <li class="navigation__item"><%= link "Manage building", to: Routes.building_path(@conn, :edit), class: "navigation__link"%></li>
                    <%= if @current_user.building do %>
                      <%= if skyscraper_active?(@current_user.building) do %>
                        <li class="navigation__item"><%= link @current_user.building.name, to: Routes.live_path(@conn, SkyscraperWeb.ConstructLive, @current_user.building.name), class: "navigation__link" %></li>
                        <li class="navigation__item"><%= link "Stop elevators ", to: Routes.construct_path(@conn, :destroy), method: :delete, class: "navigation__link" %></li>
                      <% else %>
                        <li class="navigation__item"><%= link "Start elevators ", to: Routes.construct_path(@conn, :create), method: :post, class: "navigation__link" %></li>
                      <% end %>
                    <% end %>
                  <% else %>
                    <li class="navigation__item"><%= link "Register", to: Routes.pow_registration_path(@conn, :new), class: "navigation__link" %></li>
                    <li class="navigation__item"><%= link "Sign in", to: Routes.pow_session_path(@conn, :new), class: "navigation__link" %></li>
                  <% end %>
                </ul>
            </nav>
            <button class="header__burger burger">
                <span></span>
            </button>
        </div>
    </header>

    <main class="main">
      <%= @inner_content %>
    </main>
  </body>
</html>